spring:
  application:
    name: notificator
  main:
    allow-bean-definition-overriding: true

  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVER:192.168.1.3:9092}
    topics:
      discord: ${TOPIC_DISCORD:discord-messages}
      telegram: ${TOPIC_TELEGRAM:telegram-messages}
      mail: ${TOPIC_MAIL:mail-messages}
      alexa: ${TOPIC_ALEXA:alexa-messages}
    group-id: notificator-group

  mail:
    host: ${SMTP_SERVER:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${EMAIL_USERNAME:julian.rss.android@gmail.com}
    password: ${EMAIL_PASSWORD:eqcu jplq okul xqzz}

server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/api}

discord:
  webhook-url: ${DISCORD_WEBHOOK_URL:https://discord.com/api/webhooks/1434849038586609758/Iru_TKLtmXNXyaheORsntKlBDYb7_35j_GpcG7BdoN3smld4dAPqNbExX5XJSwVcDGY-}

telegram:
  proxy-url: ${TELEGRAM_PROXY_URL:http://192.168.1.3:8080/bot8254359368:AAEJ7mG6eU_h8aToXq9KDw4WkHuHJWgqer0/sendMessage}
  chat-id: ${TELEGRAM_ID_CHAT:6610892}
  chat-id-group: ${TELEGRAM_ID_GROUP:-1001236662890}

mail:
  to: ${EMAIL_TO:julian_gomez_fdez@yahoo.es}
  subject: ${EMAIL_SUBJECT:Notificaci√≥n por email}

logging:
  file:
    path: ${LOG_PATH:/var/logs/}
    name: ${spring.application.name}
  level:
    com.julian: ${LOG_LEVEL_APP:DEBUG}
    org.springframework.boot: ${LOG_LEVEL_SPRING_BOOT:INFO}
    org.springframework.web: ${LOG_LEVEL_SPRING_WEB:INFO}
