spring:
  application:
      name: notificator
  kafka:
    bootstrap-servers: 192.168.1.3:9092
    consumer:
      group-id: discord-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      ack-mode: record
      retry:
        topic:
          enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: julian.rss.android@gmail.com
    password: eqcu jplq okul xqzz
    properties:
      mail:
       smtp:
         auth: true
         starttls:
            enable: true
            required: true
kafka:
  topics:
    discord: discord-messages
    telegram: telegram-messages
    mail: mail-messages
    alexa: alexa-messages
  group-id: notificator-group
              
discord:
  webhook-url: "https://discord.com/api/webhooks/1434849038586609758/Iru_TKLtmXNXyaheORsntKlBDYb7_35j_GpcG7BdoN3smld4dAPqNbExX5XJSwVcDGY-"
  
telegram:
 proxy-url: "http://192.168.1.3:8080/bot8254359368:AAEJ7mG6eU_h8aToXq9KDw4WkHuHJWgqer0/sendMessage"
 chat-id: "6610892"
 chat-id-group: "-1001236662890"

mail:
  to: "julian_gomez_fdez@yahoo.es"
  subject: "Notificaci√≥n por email"  
  
server:
  port: 8081
  servlet:
    context-path: /api
    
logging:
  file:
    path: ./target/
    name: ${spring.application.name}
    level:
      com.julian: DEBUG
      org.springframework.boot: INFO
      org.springframework.web: INFO

springdoc:
   swagger-ui:
     operationsSorter: alpha
     tagsSorter: alpha
          